version: "2.1"
services:
  tickbybit:
    image: tickbybit
    container_name: tickbybit
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DIRPATH=${BOT_DIRPATH}
      - BOT_CHAT_ID=${BOT_CHAT_ID}
      - ALLOWED_USERS=${ALLOWED_USERS}
    volumes:
      - settings:/app/.settings
    restart: unless-stopped

volumes:
  settings:
