version: "2.1"
services:
  tickbybit:
    image: tickbybit
    container_name: tickbybit
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SETTINGS_FILE=${SETTINGS_FILE}
      - TICKERS_DIR=${TICKERS_DIR}
      - PRICE_TTL=${PRICE_TTL}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - DOWNLOAD_PERIOD=${DOWNLOAD_PERIOD}
      - PRUNE_PERIOD=${PRUNE_PERIOD}
      - ALERT_PERIOD=${ALERT_PERIOD}
    volumes:
      - settings:/app/.settings
      - tickers:/app/.tickers
    restart: unless-stopped

volumes:
  settings:
  tickers:
