[project]
name = "tickbybit"
version = "5.0.1"

dependencies = [
    "httpx",
    "jsonpath-ng",
    "aiofiles",
    "aiogram",
    "pyyaml",
    "apscheduler",
]

[tool.coverage.run]
omit = [
    "src/tickbybit/models/settings/**/__init__.py",
]
